name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: show projects
        run: ls -la

      - name: checkout project
        uses: actions/checkout@v2
        with:
          node-version: '12'

      - name: resolve dependencies
        run: npm ci

      - name: running tests
        run: npm test -- --coverage
        env:
          CI: true